version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: "telegram_postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "telegram_bot"
    ports:
      - "8080:8080"